import type { Metadata } from "next";
import "./styles/globals.css";
import HoverGradientNavBar from "./UI/components/navbar/hover-gradient-nav-bar";
import { DarkGradientBg } from "@/app/UI/elegant-dark-pattern";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className="min-h-full flex flex-col">
                <DarkGradientBg>
                    {children}
                    <HoverGradientNavBar />
                </DarkGradientBg>
            </body>
        </html>
    );
}
