import type { Metadata } from "next";
import "./styles/globals.css";
import HoverGradientNavBar from "./UI/components/navbar/hover-gradient-nav-bar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className="min-h-full flex flex-col">
                {children}
                <HoverGradientNavBar />
            </body>
        </html>
    );
}
